import type { NewGift } from "./types";

/**
 * Placeholder gifts. Edit freely, then run `npm run seed` to (re)write
 * them to Firestore. Re-running the seed script only touches gifts
 * whose id is unchanged; see scripts/seed.mjs.
 */
export const SEED_GIFTS: (NewGift & { id: string })[] = [
  {
    id: "stand-mixer",
    name: "Stand Mixer",
    category: "Kitchen",
    price: 22000,
    desc: "For the sourdough phase we both keep threatening to start.",
    blocked: false,
    blockedAt: null,
    salt: null,
    pinHash: null,
  },
  {
    id: "espresso-machine",
    name: "Espresso Machine",
    category: "Kitchen",
    price: 32000,
    desc: "So our mornings run on something other than instant coffee.",
    blocked: false,
    blockedAt: null,
    salt: null,
    pinHash: null,
  },
  {
    id: "cast-iron-set",
    name: "Cast Iron Cookware Set",
    category: "Kitchen",
    price: 9500,
    desc: "Three pans that will outlive us both.",
    blocked: false,
    blockedAt: null,
    salt: null,
    pinHash: null,
  },
  {
    id: "bedsheet-set",
    name: "Egyptian Cotton Bedsheet Set",
    category: "Home & Living",
    price: 6800,
    desc: "Crisp, cool, and worth the splurge neither of us would make alone.",
    blocked: false,
    blockedAt: null,
    salt: null,
    pinHash: null,
  },
  {
    id: "bar-cart",
    name: "Brass Bar Cart",
    category: "Home & Living",
    price: 21000,
    desc: "For hosting the people who couldn't make it to the wedding.",
    blocked: false,
    blockedAt: null,
    salt: null,
    pinHash: null,
  },
  {
    id: "dinnerware-set",
    name: "12-Piece Dinnerware Set",
    category: "Dining",
    price: 13500,
    desc: "Matching plates, finally, instead of whatever survived our old flats.",
    blocked: false,
    blockedAt: null,
    salt: null,
    pinHash: null,
  },
  {
    id: "wine-glasses",
    name: "Crystal Wine Glasses, Set of 6",
    category: "Dining",
    price: 7200,
    desc: "For anniversaries, and also just Tuesdays.",
    blocked: false,
    blockedAt: null,
    salt: null,
    pinHash: null,
  },
  {
    id: "smart-speaker",
    name: "Smart Home Speaker",
    category: "Electronics",
    price: 8500,
    desc: "To settle arguments about facts and play music while we cook.",
    blocked: false,
    blockedAt: null,
    salt: null,
    pinHash: null,
  },
  {
    id: "robot-vacuum",
    name: "Robot Vacuum",
    category: "Electronics",
    price: 24000,
    desc: "A third roommate, one who actually does the cleaning.",
    blocked: false,
    blockedAt: null,
    salt: null,
    pinHash: null,
  },
  {
    id: "getaway-voucher",
    name: "Weekend Getaway Voucher",
    category: "Experiences",
    price: 16000,
    desc: "A trip we'll actually book instead of just talking about.",
    blocked: false,
    blockedAt: null,
    salt: null,
    pinHash: null,
  },
  {
    id: "cooking-class",
    name: "Couples Cooking Class",
    category: "Experiences",
    price: 6000,
    desc: "Two people who cannot follow a recipe, supervised.",
    blocked: false,
    blockedAt: null,
    salt: null,
    pinHash: null,
  },
  {
    id: "photo-frame-set",
    name: "Custom Photo Frame Set",
    category: "Keepsakes",
    price: 4500,
    desc: "Somewhere to put the wedding photos besides our phones.",
    blocked: false,
    blockedAt: null,
    salt: null,
    pinHash: null,
  },
];
